apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    purpose: pod-affinity
    app-name: pod-1
spec:
  containers:
  - name: pod-1
    image: nginx

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    purpose: pod-affinity
    app-name: pod-2
spec:
  affinity:
    podAffinity:
      # requiredDuringSchedulingIgnoredDuringExecution:
      # - labelSelector:
      #     matchExpressions:
      #     - key: app-name
      #       operator: In  
      #       values:
      #       - pod-1
      #   topologyKey: kubernetes.io/hostname
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app-name
              operator: In  
              values:
              - pod-1
          topologyKey: kubernetes.io/hostname
  containers:
  - name: pod-2
    image: nginx
